global:
  scrape_interval:     5s # How frequently to scrape targets by default.
  evaluation_interval: 15s # How frequently to evaluate rules by default.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'your_application'
    static_configs:
      - targets: ['deal-tracker:8080']
    metrics_path: '/hello/metrics'
